from django.urls import path
from . import views

urlpatterns = [
    path('adminLogin/', views.adminLogin,name='adminLogin'),
    path('adminLogout/', views.adminLogout,name='adminLogout'),
    path('adminProduct/', views.adminProduct,name='adminProduct'),
    path('adminCustomer/', views.adminCustomer,name='adminCustomer'),
    path('adminOrder/', views.adminOrder,name='adminOrder'),
    path('adminDashboard/', views.adminDashboard,name='adminDashboard'),
    path('adminaddProduct/', views.addProduct,name='addProduct'),
    path('adminaddVariants<int:product_id>/', views.addVariants,name='addVariants'),
    path('adminCategory/', views.adminCategory,name='adminCategory'),
    path('adminsearchCategory/', views.searchCategory,name='searchCategory'),
    path('admindeleteCategory<int:id>/', views.deleteCategory,name='deleteCategory'),
    path('adminunblockCategory<int:id>/', views.unblockCategory,name='unblockCategory'),
    path('adminaddCategory/', views.addCategory,name='addCategory'),
    path('admindeleteProduct/<int:id>', views.deleteProduct,name='deleteProduct'),
    path('admindeleteVariant/<int:id>', views.deleteVariant,name='deleteVariant'),
    path('adminsearchProduct/', views.searchProduct,name='searchProduct'),
    path('admineditProduct/<int:product_id>/', views.editProduct,name='editProduct'),
    path('admineditVariant/<int:variant_id>/', views.editVariant,name='editVariant'),
    path('admineditCategory/<int:id>/', views.editCategory,name='editCategory'),
    path('adminblockUser/<int:id>/', views.blockUser,name='blockUser'),
    path('adminunblockUser/<int:id>/', views.unblockUser,name='unblockUser'),
    path('adminsearchUser/', views.searchUser,name='searchUser'),
    path('admineditOrder/<int:id>/', views.admineditOrder,name='admineditOrder'),
    path('adminsearchOrder/', views.searchOrder,name='searchOrder'),
    path('adminCoupon/', views.adminCoupon,name='adminCoupon'),
    path('adminaddCoupon/', views.addCoupon,name='addCoupon'),
    path('admineditCoupon/<int:coupon_id>/', views.editCoupon,name='editCoupon'),
    path('admindeleteCoupon/<int:coupon_id>/', views.deleteCoupon,name='deleteCoupon'),
    path('adminsearchCoupon/', views.searchCoupon,name='searchCoupon'),
    path('adminOffers/', views.adminOffers,name='adminOffers'),
    path('addProductOffer/', views.addProductOffer,name='addProductOffer'),
    path('addCategoryOffer/', views.addCategoryOffer,name='addCategoryOffer'),
    path('admineditOffer/<str:offer_type>/<int:id>/', views.editOffer, name='editOffer'),
    path('admindeleteOffer/<str:offer_type>/<int:id>/', views.deleteOffer, name='deleteOffer'),
    path('admindownloadReport/', views.downloadReport, name='downloadReport'),
    path('adminmanageRequests/', views.manageRequests, name='manageRequests'),
    path('admintopSellers/', views.topSellers, name='topSellers'),
    path('chart-data/', views.chart_data, name='chart_data'), 
    

]