# Generated by Django 5.1.1 on 2024-10-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category_variant_categoryoffer_product_offer_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
