# Generated by Django 5.1.1 on 2024-10-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.variant'),
        ),
    ]
