# Generated by Django 5.1.1 on 2024-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_product_variant_remove_product_variant_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
