# Generated by Django 5.1.1 on 2024-10-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
    ]
