# Generated by Django 5.1.1 on 2024-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_rename_shipping_adress_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_recieved', 'Order Recieved'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='order_recieved', max_length=20),
        ),
    ]
