# Generated by Django 5.1.1 on 2024-11-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_product_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
