# Generated by Django 5.1.1 on 2024-11-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_productvariant_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
