# Generated by Django 5.1.1 on 2024-11-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0034_remove_product_popularity_productvariant_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
