# Generated by Django 5.1.1 on 2024-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashOnDelivery', 'Cash on Delivery'), ('razorPay', 'RazorPay')], default='cashOnDelivery', max_length=20),
        ),
    ]
