# Generated by Django 5.1.1 on 2024-11-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_orderitem_placed_at_alter_cart_user_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
