# Generated by Django 5.1.1 on 2024-11-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_coupon_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adminapp.productvariant'),
        ),
    ]
