# Generated by Django 5.1.1 on 2024-11-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_offer_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
