# Generated by Django 5.1.1 on 2024-11-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0045_productvariant_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cashOnDelivery', 'Cash on Delivery'), ('razorPay', 'RazorPay'), ('wallet', 'Wallet')], default='cashOnDelivery', max_length=20),
        ),
    ]
